### ISSUE TITLE
语义分割相关的一些问题

### ISSUE THREAD

**Issue by bjchen666** [lxtGH/dfn_seg#1]
你好，我是厦门大学研一的学生，也是做语义分割的，碰到了一些问题，不知道你是否方便留个联系方式，我想请教你一些问题，谢谢！

**Comment by lxtGH** [comment]
你好！我也是研究生第一年，也只是做了3月，可以讨论下问题（虽然我回答也不一定准确）~

在2018-07-27 11:48:59，gshdongnotifications@github.com写道：

你好，我是厦门大学研一的学生，也是做语义分割的，碰到了一些问题，不知道你是否方便留个联系方式，我想请教你一些问题，谢谢！
