### ISSUE TITLE
Global Pooling and Upsample

### ISSUE THREAD

**Issue by chenyzh28** [lxtGH/dfn_seg#2]
在Global Pooling后得到了1X1的向量，利用nn.Upsample上采样的时候报错：RuntimeError: input aspect ratio does not match the output ratio. 难道上采样的时候输入输出的长宽比要相同吗？那1X1怎么上采样为12*16呢？

**Comment by lxtGH** [comment]
有一个size的选项,你可以查下upsampling 的api
