### ISSUE TITLE
The defined res101 model is different from the pytorch model ZOO

### ISSUE THREAD

**Issue by irfanICMLL** [lxtGH/dfn_seg#3]
You define the layer0 of the class DFN with two convs and two bn, but the resnet101 in the pytorch model ZOO only has one conv in the first layer, when I am using the pytorch 0.4.1.

Maybe you use another model file when you write the paper?

Can you share the model parameters and the Gflops?

**Comment by lxtGH** [comment]
Yes, you are right, this resnet can be acessed from this [link](http://sceneparsing.csail.mit.edu/model/pytorch/) and a little Gflops than original pytorch model
